[board]
sysclk = { mode = "Z",    pullup = true,  invert = false }
dclk   = { mode = "Z",    pullup = true,  invert = false }
data   = { mode = "Z",    pullup = true,  invert = false }
pwramp = { mode = "TCXO", pullup = false, invert = false }
irq    = { mode = "IRQ",  pullup = false, invert = false }
antsel = { mode = "Z",    pullup = true,  invert = false }
xtal = { kind = "TCXO", freq = 48_000_000, enable = "AntSel" }
vco = "Internal"
filter = "Internal"
dac = { pin = "PwrAmp" }
adc = "ADC1"

[synth]
freq_a = 505_000_000
freq_b = 0
active = "A"
pll = { charge_pump_current = 0x02, filter_bandwidth = "Internalx1" }
boost = { charge_pump_current = 0xc8, filter_bandwidth = "Internalx5" }
vco_current = "Automatic"
lock_detector_delay = "Automatic"
ranging_clock = "XtalDiv1024"

[[channel]]
modulation.GMSK = { ramp = "Bits1", bt = 0.5 }
encoding = "NRZISCR"
framing.HDLC.fec = {}
crc.CCITT.initial = 0xFFFF
datarate = 60_000
bitorder = "MSBFirst"

[tx]
antenna = "SingleEnded"
amp.RaisedCosine = { a = 0, b = 0x700, c = 0, d = 0, e = 0 }
plllock_gate = true
brownout_gate = true
