[package]
name = "ax5043"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ax5043_derive = { path = "../ax5043_derive" }
bitflags = "1.3.2"
clap = { version = "4.2.2", features = ["derive"] }
ctrlc = "3.2.5"
gpiod = "0.2.3"
mio = { version = "0.8.6", features = ["net", "os-poll"] }
spidev = "0.5.1"
