[board]
sysclk = { mode = "Z",      pullup = true,  invert = false }
dclk   = { mode = "Z",      pullup = true,  invert = false }
data   = { mode = "Z",      pullup = true,  invert = false }
pwramp = { mode = "PwrAmp", pullup = false, invert = false }
irq    = { mode = "IRQ",    pullup = false, invert = false }
antsel = { mode = "Z",      pullup = true,  invert = false }
xtal = { kind = "TCXO", freq = 16_000_000, enable = "None" }
vco = "Internal"
filter = "Internal"
dac = { pin = "None" }
adc = "None"

[synth]
freq_a = 436_500_000
freq_b = 0
active = "A"
pll = { charge_pump_current = 0x02, filter_bandwidth = "Internalx1" }
boost = { charge_pump_current = 0xC8, filter_bandwidth = "Internalx5" }
vco_current = "Automatic"
lock_detector_delay = "Automatic"
ranging_clock = "XtalDiv1024"

[[channel]] # EDL
modulation.GMSK = { ramp = "Bits1", bt = 0.5 }
encoding = "NRZISCR"
framing.HDLC.fec = { }
crc.CCITT = { initial=0xFFFF }
datarate = 96_000
bitorder = "MSBFirst"

[[channel]] # Beacon
modulation.GMSK = { ramp = "Bits1", bt = 0.5 }
encoding = "NRZISCR"
framing.HDLC.fec = { }
crc.CCITT = { initial=0xFFFF }
datarate = 9_600
bitorder = "LSBFirst"

[tx]
antenna = "SingleEnded"
amp.RaisedCosine = { a = 0, b = 0x700, c = 0, d = 0, e = 0 }
plllock_gate = true
brownout_gate = true

[rx.MSK]
max_dr_offset = 0
freq_offs_corr = "AtFirstLO"
ampl_filter = 0
frequency_leak = 0

[set0]
agc = "Automatic"
decay = 0x6
baseband_offset = { a = 0, b = 0 }

[set0.gain]
time_corr_frac = 4
datarate_corr_frac = 255
phase = 0x03
filter = 0x03
amplitude = 0x06
deviation_update = true
ampl_agc_jump_correction = false
ampl_averaging = false

[set3]
agc = "Automatic"
decay = 0x6
baseband_offset = { a = 0, b = 0 }

[set3.gain]
time_corr_frac = 32
datarate_corr_frac = 1024
phase = 0x03
filter = 0x03
amplitude = 0x06
deviation_update = true
ampl_agc_jump_correction = false
ampl_averaging = false

[stages]
preamble1 = { timeout = { m = 0x17, e = 5 }, set = "Set0" }
packet = "Set3"

