# Reference:
# - https://doc.rust-lang.org/stable/clippy/continuous_integration/github_actions.html
# - https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
on: push

name: Build and Test

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --examples --bins --lib --verbose
      - name: Run fmt
        run: cargo fmt
